import jobData from '../data/jobs.json';
import { GetStaticProps } from 'next'
import JobDataType from "./types/JobDataType";
import IndexView from "../views/IndexView";

interface Props {
    data: any
}

export const getStaticProps: GetStaticProps<Props> = async () => {
    const data:JobDataType[] = jobData;
    return { props: { data } }
}


export default function Home({data }: Props) {

  return (
      <IndexView />
    // <div className={styles.container}>
    //   <Head>
    //     <title>Byorns Playground</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //
    //   <Navbar />
    //   <main className={styles.main}>
    //
    //
    //
    //       { data.map((job: JobDataType) => <div key={job.jobId}>{job.jobId} <MUILink  component={Link} href={`job-details/${job.jobId}`}>{job.jobDescription}</MUILink></div>) }
    //
    //   </main>
    //
    //
    // </div>
  )
}
